name: Code Coverage
on:
  pull_request:
    branches:
      - develop
      - feature/QR202311

jobs:
  run-code-coverage:
    name: Code Coverage Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run coverage