name: Code Coverage
on:
  pull_request:
    branches:
      - develop
      - feature/QR**

jobs:
  run-code-coverage:
    name: Code Coverage Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run test:report
      # - name: Code Coverage Report
      #   uses: irongut/CodeCoverageSummary@v1.3.0
      #   with:
      #     filename: coverage/**/cobertura-coverage.xml
      #     badge: true
      #     format: markdown
      #     hide_branch_rate: false
      #     hide_complexity: true
      #     indicators: true
      #     output: both
      #     thresholds: '60 80'
      #     fail_below_min: false
      # - name: Add Coverage PR Comment

      # - name: Display coverage
      #   uses: ewjoachim/coverage-comment-action@v1
      #   with:
      #     GITHUB_TOKEN: ${{ github.token }}
      #     COVERAGE_FILE: coverage/cobertura-coverage.xml

      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        with:
          github-token: ${{ github.token }}
          # barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "./coverage/lcov.info"
          # base-lcov-file: "./lcov.info"
          # minimum-ratio: 0 # Fails Github action once code coverage is decreasing
          send-summary-comment: true
          show-annotations: "warning" # Possible options warning|error
          app-name: 'uex-ess'