name: QR
on:
  push:
    branches:
      - feature/QR202311

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run test:report
      - name: Coverage Badge
        uses: we-cli/coverage-badge-action@v1.0.1
      - run: npm run build